### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by chriseth** [ethereum/source-verify#11]
The server-side component should report why something went wrong and how much it was able to do so far.

**Comment by edisinovcic** [comment]
@cgewecke I think you covered this in your PR?

**Comment by cgewecke** [comment]
@edisinovcic Just checked and there are a couple of possible errors that could get better handling.
+ [inject:recompile][1] 
+ [inject:getBytecode][2]

...should prob. have any errors they throw wrapped with a more formal message.

Self-assigning.



[1]: https://github.com/ethereum/source-verify/blob/master/src/injector.ts#L212
[2]: https://github.com/ethereum/source-verify/blob/dc38618d0e7c75228d8aa07d5da0da4b6b976138/src/injector.ts#L215

**Comment by edisinovcic** [comment]
Maybe adding one global error handler and then throwing custom errors?

**Comment by cgewecke** [comment]
@edisinovcic Ah interesting - yes that looks good for the server.js. 

I was thinking of something for the libs that more like a utility where all the messages are maintained/wrapped. 
```
util.throwError('compiler:download-failed', err)  
```

**Comment by edisinovcic** [comment]
Yeah, that would be better as server is not that big and we don't need many custom errors. 

Maybe it's good idea to specify in the documentation all the kinds of errors that could exists? That are valid errors of course.

One of the ideas I have was to later add monitoring for both staging and production (https://github.com/ethereum/source-verify/issues/64) and if some not valid errors happen we could show that to the users in chat (for example gitter) and receive a notification that something is wrong with it. 

It's part of continuously monitoring of the services so that we don't learn from users that something is down, but rather get a notification as soon as some service goes down or shows repeated error.

Also option is that you implement it and just add error at the end to the doc that are possible.

**Comment by edisinovcic** [comment]
@cgewecke can you also add a timestamp to output so we can more easily do diagnostics if something happens with service?

**Comment by cgewecke** [comment]
#84 timestamp is part of the JSON output now. 

Logs also have 
+ a `name` field that corresponds to the module, e.g `Injector`
+ a `loc` field telling you ~ where the log was written from in the code (which method).
+ if log is an err, there will be a defined `err` field and a `message` field with the error text.
   + `if (log.err) console.log(log.message)`
