### ISSUE TITLE
Create and run geth on goerli inside docker

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/source-verify#97]
* https://github.com/chriseth/go-ethereum (make and build into docker container)
* https://github.com/goerli/testnet/blob/master/geth/goerli.genesis (genesis file)

What ports need to be exposed?
* Define it in toml file so it's easier to maintain.

**Comment by ligi** [comment]
oh - it must be on a different machine. We cannot run nodes on that one - it would just be overloaded.

**Comment by edisinovcic** [comment]
Referencing discussion from geth fork:
https://github.com/chriseth/go-ethereum/pull/1

Currently supported networks via cli:
mainnet (by default)
* --testnet (Ropsten)
* --rinkeby
* --goerli

Do we want to support some other?

**Comment by edisinovcic** [comment]
For the reference: https://blog.ethereum.org/2019/07/10/geth-v1-9-0/

![full_node](https://user-images.githubusercontent.com/16107679/77749153-d2bc2a00-7021-11ea-81c4-7665f5f33f52.png)

**Comment by edisinovcic** [comment]
It's been implemented and working. Closing this if you @ligi agree.
It's also been implemented to work with other networks.

**Comment by tjayrush** [comment]
I'm most familiar with running Parity archive or tracing nodes. I run two `--pruning archive` nodes on two identically build Ubuntu linux boxes in my home offices. I basically went to the local computer store and told them to build me a 'good gaming machine.' The only real change I made was about six months ago -- I had them install an 8TB RAID drive because the hard disc storage for the archive node was getting terribly close to 4TB (which was how large the hard drive was before). Currently (at block 9,821,135) it's taking up 4,119,192,804 bytes on the hard drive. That shouldn't be an issue for your, as you're only running a full node.

As far as the compute, I think once the node is synced, it will take next to no compute -- one block every fourteen seconds leaves an infinite amount of extra computer.

Your biggest issue is going to be bandwidth for the syncing, but once it's synced I don't see bandwidth being a problem -- if I understand what you're doing, you won't be querying the chain directly -- only just monitoring and scraping.

Is there some Linux command line I could run to get a better ides of my machine's specs?

**Comment by edisinovcic** [comment]
@tjayrush this is a good start for it: https://www.binarytides.com/linux-commands-hardware-info/

**Comment by yashbhavsar007** [comment]
What will be the command/flag for docker to make it runnable for goerli testnet?

**Comment by edisinovcic** [comment]
@yashbhavsar007 you have --goerli flag. More on it here: https://geth.ethereum.org/docs/interface/command-line-options

**Comment by yashbhavsar007** [comment]
Okay @edisinovcic So, the command must be ```docker run -it -p 30303:30303 ethereum/client-go --goerli```. I'll try this one. Thank You.

**Comment by edisinovcic** [comment]
@yashbhavsar007 best chat to ask these questions would be official geth discord https://discord.com/invite/nthXNEv.
